<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40923" started-at="2013-02-11T09:16:39Z" finished-at="2013-02-11T09:17:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40923" started-at="2013-02-11T09:16:39Z" finished-at="2013-02-11T09:17:20Z">
      <class name="com.YouMagicPro.LKS_tests.PhoneSearchBySymbols">
        <test-method status="PASS" signature="startWebDriver()[pri:0, instance:com.YouMagicPro.LKS_tests.PhoneSearchBySymbols@33462704]" name="startWebDriver" is-config="true" duration-ms="1875" started-at="2013-02-11T13:16:39Z" finished-at="2013-02-11T13:16:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWebDriver -->
        <test-method status="FAIL" signature="phoneSearchBySymbols_C15338()[pri:0, instance:com.YouMagicPro.LKS_tests.PhoneSearchBySymbols@33462704]" name="phoneSearchBySymbols_C15338" duration-ms="36499" started-at="2013-02-11T13:16:41Z" finished-at="2013-02-11T13:17:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [x3 B1
322] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [x3 B1
322] but found []
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at com.YouMagicPro.LKS_tests.TestBase.assertEquals(TestBase.java:52)
	at com.YouMagicPro.LKS_tests.PhoneSearchBySymbols.phoneSearchBySymbols_C15338(PhoneSearchBySymbols.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneSearchBySymbols_C15338 -->
        <test-method status="PASS" signature="closeSession()[pri:0, instance:com.YouMagicPro.LKS_tests.PhoneSearchBySymbols@33462704]" name="closeSession" is-config="true" duration-ms="2536" started-at="2013-02-11T13:17:17Z" finished-at="2013-02-11T13:17:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeSession -->
      </class> <!-- com.YouMagicPro.LKS_tests.PhoneSearchBySymbols -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
